development:
  host: pophdevhadoopmstr02.northamerica.cerner.net
  port: 50070
  username: webhdfs-ruby-streamer_app
test:
  host: pophdevhadoopmstr02.northamerica.cerner.net
  port: 50070
  username: webhdfs-ruby-streamer_app
production:
  host: pophdevhadoopmstr02.northamerica.cerner.net
  port: 50070
  username: webhdfs-ruby-streamer_app
